// Deterministic mock data for Agent Builder › Actions. The source design is
// the August 2026 Actions refresh (Figma node 48:17773); there is no backend.

export type ToolTab = 'Available' | 'Recommended' | 'Authentication' | 'History'
export const TOOL_TABS: ToolTab[] = ['Available', 'Recommended', 'Authentication', 'History']

export type ToolType = 'API' | 'Imported' | 'MCP' | 'Browser'
export type ToolState = 'Live' | 'Read only' | 'Auto-saved'

export type ToolAction = {
  id: string
  name: string
  detailTitle?: string
  description: string
  type: ToolType
  iconTint: 'blue' | 'slate'
  useCase: string | null
  conversations: number
  state: ToolState
  lastModified: string
  method?: 'GET' | 'POST'
  endpoint?: string
  inputParameters?: string[]
  outputParameters?: string[]
}

// Both counts are labels supplied by the design, not derived from the mock rows.
export const NAME_COUNT = 113
export const RUN_COUNT = 113

const MODIFIED = 'Feb 13, 2026, 12:43 PM'

export const TOOL_ACTIONS: ToolAction[] = [
  {
    id: 't1',
    name: 'Get full account information by customer ID',
    description: "Look up a customer's full account details",
    type: 'API',
    iconTint: 'blue',
    useCase: 'Account details',
    conversations: 100,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't2',
    name: 'Get earnings',
    description: "Retrieve a driver's or seller's earnings data.",
    type: 'Imported',
    iconTint: 'slate',
    useCase: 'Earnings questions',
    conversations: 40,
    state: 'Read only',
    lastModified: MODIFIED,
  },
  {
    id: 't3',
    name: 'Reconcile payout',
    detailTitle: 'Reconcile Payout',
    description:
      'Merchant action. Payout reconciliation view. Returns period totals and any discrepancies.',
    type: 'Imported',
    iconTint: 'slate',
    useCase: 'Merchant +4',
    conversations: 1_000,
    state: 'Live',
    lastModified: MODIFIED,
    method: 'GET',
    endpoint: 'https://api.cashwise.example/merchant/payouts/reconcile?store_id=$HH_Test_Store_ID',
    inputParameters: ['Store ID'],
    outputParameters: [],
  },
  {
    id: 't4',
    name: 'Get flight',
    description: 'Retrieve flight details and status',
    type: 'MCP',
    iconTint: 'blue',
    useCase: 'Flight status',
    conversations: 950,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't5',
    name: 'Get Cart',
    description: "Retrieve the current items in a customer's cart",
    type: 'Browser',
    iconTint: 'blue',
    useCase: null,
    conversations: 200,
    state: 'Auto-saved',
    lastModified: MODIFIED,
  },
  // ── Actions the seeded use-case policies name ────────────────────────────
  // Everything above is transcribed from the Actions refresh frame. The rows
  // below exist because a policy in policy-seeds.ts names them in an `action`
  // chip, and a chip whose label matches no catalog row reads as a broken
  // reference when you click through from the policy to the Actions screen.
  // The first three are named by the Figma-transcribed Service cancellation
  // policy, which predates this catalog.
  {
    id: 't6',
    name: 'Apply 30-Day Free',
    description: 'Credit 30 days of service to a retained account.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Service cancellation',
    conversations: 2_100,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't7',
    name: 'Schedule Day-30 Check-in',
    description: 'Queue a follow-up outreach for the end of a retention credit.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Service cancellation',
    conversations: 1_180,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't8',
    name: 'Process Cancellation',
    description: 'Close the subscription at the end of the current billing period.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Service cancellation',
    conversations: 1_652,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't9',
    name: 'Create Support Ticket',
    description: 'Open a ticket with the transcript and any collected context attached.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Fallback +3',
    conversations: 5_310,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't10',
    name: 'Send Sign-in Link',
    description: 'Email a single-use sign-in link that expires in 15 minutes.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Login Help +1',
    conversations: 3_940,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't11',
    name: 'Email Tax Document',
    description: "Send a copy of an annual summary or 1099 to the account's address on file.",
    type: 'Imported',
    iconTint: 'slate',
    useCase: 'Tax document processing',
    conversations: 958,
    state: 'Read only',
    lastModified: MODIFIED,
  },
  {
    id: 't12',
    name: 'Rotate API Key',
    description: 'Issue a replacement key and expire the old one after a grace period.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Trouble with integration',
    conversations: 411,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't13',
    name: 'Schedule Callback',
    description: 'Book an outbound call inside a window the customer picked.',
    type: 'MCP',
    iconTint: 'blue',
    useCase: 'Voicemail triage',
    conversations: 1_200,
    state: 'Live',
    lastModified: MODIFIED,
  },
  // Order Management actions
  {
    id: 't14',
    name: 'Lookup Order by Email',
    description: 'Find orders by customer email and date range.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Track order',
    conversations: 1_620,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't15',
    name: 'Get Order Status',
    description: 'Retrieve current state, location, and ETA for an order.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Track order +3',
    conversations: 3_240,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't16',
    name: 'Open Delivery Investigation',
    description: 'Create an investigation for missing or disputed deliveries.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Track order +1',
    conversations: 420,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't17',
    name: 'Update Order Address',
    description: 'Change the delivery address before dispatch.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Modify order',
    conversations: 1_264,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't18',
    name: 'Cancel Order',
    description: 'Cancel an order before dispatch and initiate refund.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Cancel order',
    conversations: 952,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't19',
    name: 'Open Item Claim',
    description: 'Create a claim for missing, damaged, or wrong items.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Report missing/damaged item',
    conversations: 833,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't20',
    name: 'Get Delivery Proof',
    description: 'Retrieve photo, signature, or GPS coordinates for a completed delivery.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Delivery proof request',
    conversations: 378,
    state: 'Live',
    lastModified: MODIFIED,
  },
  // Subscription Lifecycle actions
  {
    id: 't21',
    name: 'Pause Subscription',
    description: 'Pause billing and benefits for a selected duration.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Pause subscription',
    conversations: 612,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't22',
    name: 'Resume Subscription',
    description: 'Restore billing and benefits from a paused state.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Resume subscription',
    conversations: 306,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't23',
    name: 'Retry Payment',
    description: 'Attempt to charge a failed payment method again.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Failed payment recovery',
    conversations: 1_472,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't24',
    name: 'Change Subscription Plan',
    description: 'Upgrade or downgrade a subscription with proration.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Change plan',
    conversations: 782,
    state: 'Live',
    lastModified: MODIFIED,
  },
  // Payment Management actions
  {
    id: 't25',
    name: 'Add Payment Method',
    description: 'Store a new card or payment method securely.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Add/update payment method',
    conversations: 1_278,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't26',
    name: 'Open Charge Dispute',
    description: 'File a dispute for an unrecognized or incorrect charge.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Dispute charge',
    conversations: 624,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't27',
    name: 'Apply Promo Code',
    description: 'Validate and apply a discount code to cart or account.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Apply promo code',
    conversations: 1_890,
    state: 'Live',
    lastModified: MODIFIED,
  },
  // Safety & Trust actions
  {
    id: 't28',
    name: 'Create Safety Incident',
    description: 'Record a safety incident and flag for urgent review.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Report incident',
    conversations: 420,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't29',
    name: 'Contact Driver for Lost Item',
    description: 'Notify driver about a lost item and facilitate coordination.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Lost item recovery',
    conversations: 744,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't30',
    name: 'Submit Rating Dispute',
    description: 'Challenge an unfair rating with evidence.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Rating dispute',
    conversations: 476,
    state: 'Live',
    lastModified: MODIFIED,
  },
  // Proactive Communication actions
  {
    id: 't31',
    name: 'Apply Reengagement Credit',
    description: 'Issue a promotional credit to incentivize return usage.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Re-engage dormant account',
    conversations: 504,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't32',
    name: 'Send Emergency Notification',
    description: 'Contact a designated person with trip status or urgent message.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Emergency contact',
    conversations: 180,
    state: 'Live',
    lastModified: MODIFIED,
  },
  // Additional actions referenced by policies
  {
    id: 't33',
    name: 'Validate Delivery Address',
    description: 'Verify and format a delivery address before modification.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Modify order',
    conversations: 948,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't34',
    name: 'Modify Order Items',
    description: 'Add, remove, or change quantities of items in an order.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Modify order',
    conversations: 632,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't35',
    name: 'Get Delivery Windows',
    description: 'Retrieve available delivery time slots for an order.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Modify order',
    conversations: 421,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't36',
    name: 'Update Delivery Window',
    description: 'Change the scheduled delivery time for an order.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Modify order',
    conversations: 358,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't37',
    name: 'Initiate Return',
    description: 'Start a return process and generate return label.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Cancel order',
    conversations: 1_142,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't38',
    name: 'Email Delivery Proof',
    description: 'Send delivery confirmation evidence to customer email.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Delivery proof request',
    conversations: 284,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't39',
    name: 'Get Subscription Details',
    description: 'Retrieve current subscription status, tier, and billing info.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Pause subscription +2',
    conversations: 1_894,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't40',
    name: 'Get Available Plans',
    description: 'List all subscription plans available for upgrade or downgrade.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Change plan',
    conversations: 624,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't41',
    name: 'Calculate Proration',
    description: 'Calculate pro-rated charges or credits for plan changes.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Change plan',
    conversations: 580,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't42',
    name: 'Get Payment Methods',
    description: 'Retrieve all stored payment methods for an account.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Add/update payment method',
    conversations: 1_092,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't43',
    name: 'Update Payment Method',
    description: 'Modify details of an existing payment method.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Add/update payment method',
    conversations: 842,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't44',
    name: 'Set Default Payment Method',
    description: 'Designate which payment method to use for future charges.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Add/update payment method',
    conversations: 736,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't45',
    name: 'Lookup Charge by Amount',
    description: 'Find a specific charge by amount, date, and account.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Dispute charge',
    conversations: 468,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't46',
    name: 'Validate Promo Code',
    description: 'Check if a promo code is valid and applicable.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Apply promo code',
    conversations: 1_680,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't47',
    name: 'Save Promo Code to Account',
    description: 'Store a validated promo code to the customer account.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Apply promo code',
    conversations: 1_512,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't48',
    name: 'Get Transaction Details',
    description: 'Retrieve full details of a payment transaction.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Split payment help',
    conversations: 336,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't49',
    name: 'Retry Single Payment',
    description: 'Attempt to process a single failed payment in a split transaction.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Split payment help',
    conversations: 294,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't50',
    name: 'Get Account Activity',
    description: 'Retrieve recent account usage and transaction history.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Re-engage dormant account',
    conversations: 378,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't51',
    name: 'Reactivate Subscription',
    description: 'Restore a cancelled subscription and re-enable billing.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Resume subscription',
    conversations: 184,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't52',
    name: 'Get Payment Failure Details',
    description: 'Retrieve information about a failed payment attempt.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Failed payment recovery',
    conversations: 1_288,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't53',
    name: 'Cancel Subscription',
    description: 'Terminate an active subscription and stop future billing.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Dispute charge',
    conversations: 248,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't54',
    name: 'Get Rating Details',
    description: 'Retrieve the rating, timestamp, and feedback for a trip or interaction.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Rating dispute',
    conversations: 380,
    state: 'Live',
    lastModified: MODIFIED,
  },
  {
    id: 't55',
    name: 'Share Trip Status',
    description: 'Send live trip status and ETA to a designated emergency contact.',
    type: 'API',
    iconTint: 'blue',
    useCase: 'Emergency contact',
    conversations: 144,
    state: 'Live',
    lastModified: MODIFIED,
  },
]

/** Every action name the catalog carries, for cross-checking policy chip labels. */
export const TOOL_ACTION_NAMES: readonly string[] = TOOL_ACTIONS.map((action) => action.name)

export function findToolAction(id: string | undefined) {
  if (id === 'get-account-profile') return TOOL_ACTIONS[0]
  return TOOL_ACTIONS.find((action) => action.id === id)
}

export type RunStatus = 'In progress' | 'Completed' | 'Failed'

export type ToolRun = {
  id: string
  name: string
  description: string
  runAt: string
  type: ToolType
  channel: string
  conversationId: string | null
  status: RunStatus
}

const CONVERSATION_ID = '18c2eb33-efcd-4090-abc9-14c5fb972c12'

export const TOOL_RUNS: ToolRun[] = [
  {
    id: 'run-flight',
    name: 'Get flight',
    description: 'Retrieves flight details for a booking reference',
    runAt: 'Oct 11, 2025 9:25 AM',
    type: 'API',
    channel: 'Headless',
    conversationId: null,
    status: 'In progress',
  },
  {
    id: 'run-freeze-card-1',
    name: 'Freeze Card',
    description: "Temporarily locks a customer's card to prevent new charges",
    runAt: 'Oct 10, 2025 9:25 AM',
    type: 'API',
    channel: 'Voice',
    conversationId: CONVERSATION_ID,
    status: 'Completed',
  },
  {
    id: 'run-cart',
    name: 'Get Cart',
    description: "Fetches current items and total in a customer's cart",
    runAt: 'Oct 9, 2025 9:25 AM',
    type: 'MCP',
    channel: 'Web Call',
    conversationId: CONVERSATION_ID,
    status: 'Failed',
  },
  {
    id: 'run-freeze-card-2',
    name: 'Freeze Card',
    description: "Temporarily locks a customer's card to prevent new charges",
    runAt: 'Oct 10, 2025 9:25 AM',
    type: 'API',
    channel: 'Voice',
    conversationId: CONVERSATION_ID,
    status: 'Completed',
  },
  {
    id: 'run-account-info',
    name: 'Get Account Info',
    description: 'Pulls account details, plan tier, and standing',
    runAt: 'Oct 8, 2025 9:25 AM',
    type: 'Browser',
    channel: 'Widget',
    conversationId: CONVERSATION_ID,
    status: 'Completed',
  },
  {
    id: 'run-cancel-order',
    name: 'Cancel order',
    description: "Cancels an order if it hasn't shipped yet",
    runAt: 'Oct 10, 2025 9:25 AM',
    type: 'API',
    channel: 'Voice',
    conversationId: CONVERSATION_ID,
    status: 'Completed',
  },
]
