// Mock data + types for Agent Builder's Use cases landing screen. Widget is
// transcribed from the August 2026 Explore Unification frame; the remaining
// channels keep authored mock values so the channel switcher remains useful.

// `webcall` is the Web Call channel; `email` is the Email channel — it used to
// borrow the `webcall` key (see below), and got its own when Web Call became a
// channel of its own on this surface.
export type ChannelKey = 'widget' | 'voice' | 'webcall' | 'headless' | 'email'
export type CallDirection = 'inbound' | 'outbound'
export type Trend = 'up' | 'down'

export type Metric = {
  key: string
  label: string
  value: string
  sub?: string
  delta: string
  trend: Trend
  good: boolean
  accent?: boolean
}

export type Agent = {
  id: string
  name: string
  on: boolean
  isSubflow: boolean
  type: string
  conversations: number
  resolutions: number
  resolutionRate: string
  csat: number
  tags: string[]
  // Built-in use cases display a fixed status instead of an editable switch.
  canToggle?: boolean
  // Voice-only fields below — undefined for every other channel's agents.
  callDirection?: CallDirection
  segment?: string
  totalTalkTime?: string
  avgTalkTime?: string
  sentiment?: string
  contextVariables?: string[]
  actionsUsed?: string[]
  subUseCases?: string[]
  status?: string
  lastModified?: { at: string; by: string }
  // Voice Outbound-only (frame 112:51124): the table there prints the use
  // case's id, its segment as a coloured chip, and voicemails left.
  useCaseId?: string
  voicemailLeft?: string
  segmentColor?: string
}

export type Channel = {
  key: ChannelKey
  label: string
  metrics: Metric[]
  agents: Agent[]
  // Voice-only: the metric set shown when the Outbound tab is active.
  outboundMetrics?: Metric[]
}

export const CHANNELS: Channel[] = [
  {
    key: 'widget',
    label: 'Widget',
    metrics: [
      {
        key: 'chats',
        label: 'Total Chats',
        value: '21,590',
        delta: '0.3%',
        trend: 'down',
        good: false,
      },
      {
        key: 'resolutions',
        label: 'Resolutions',
        value: '19,673',
        sub: '80%',
        delta: '4.2%',
        trend: 'up',
        good: true,
      },
      {
        key: 'fallback',
        label: 'Fallback',
        value: '486',
        delta: '1.8%',
        trend: 'down',
        good: true,
      },
      {
        key: 'csat',
        label: 'CSAT',
        value: '4.1',
        delta: '1.7%',
        trend: 'down',
        good: false,
        accent: true,
      },
      {
        key: 'cost',
        label: 'Cost Savings',
        value: '$706,8K',
        delta: '3.4%',
        trend: 'up',
        good: true,
      },
    ],
    agents: [
      {
        id: 'w1',
        name: 'Knowledge Retrieval',
        on: true,
        isSubflow: false,
        type: 'Knowledge Retrieval',
        conversations: 19680,
        resolutions: 13813,
        resolutionRate: '84%',
        csat: 4.2,
        tags: ['Riders', 'Drivers'],
        canToggle: false,
      },
      {
        id: 'w2',
        name: 'Fallback',
        on: true,
        isSubflow: false,
        type: 'Fallback',
        conversations: 3762,
        resolutions: 593,
        resolutionRate: '97%',
        csat: 2.4,
        tags: ['Riders', 'Drivers', 'Couriers'],
        canToggle: false,
      },
      {
        id: 'w3',
        name: 'Service cancellation',
        on: true,
        isSubflow: true,
        type: 'With intent',
        conversations: 4591,
        resolutions: 2939,
        resolutionRate: '86%',
        csat: 4.1,
        tags: ['One members'],
      },
      {
        id: 'w4',
        name: 'Login Help',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 2845,
        resolutions: 1296,
        resolutionRate: '56%',
        csat: 4.3,
        tags: ['Riders', 'Drivers', 'Eats customers'],
      },
      {
        id: 'w5',
        name: 'Tax document processing',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1034,
        resolutions: 958,
        resolutionRate: '95%',
        csat: 4.1,
        tags: ['Drivers', 'Couriers'],
      },
      {
        id: 'w6',
        name: 'Trouble with integration',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 589,
        resolutions: 590,
        resolutionRate: '89%',
        csat: 4.1,
        tags: ['Business riders'],
      },
      {
        id: 'w7',
        name: 'Product recommendations',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 543,
        resolutions: 519,
        resolutionRate: '75%',
        csat: 3.2,
        tags: ['Riders', 'Eats customers', 'One members', 'Business riders'],
      },
      // The agent AI Studio's self-improving plan diagnoses (see
      // ai-studio/self-improving/self-improving-data.ts). Its figures are the
      // plan's own scorecard: 34% deflection, 1.3 CSAT — the plan and the table
      // must not disagree about the agent they describe.
      {
        id: 'w8',
        name: 'Password Reset',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1910,
        resolutions: 649,
        resolutionRate: '34%',
        csat: 1.3,
        tags: ['Riders', 'Drivers'],
      },
      // Order Management agents — the critical gap identified in gap analysis
      {
        id: 'w9',
        name: 'Track order',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 3240,
        resolutions: 2916,
        resolutionRate: '90%',
        csat: 4.3,
        tags: ['Eats customers', 'Riders'],
      },
      {
        id: 'w10',
        name: 'Modify order',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1580,
        resolutions: 1264,
        resolutionRate: '80%',
        csat: 4.0,
        tags: ['Eats customers'],
      },
      {
        id: 'w11',
        name: 'Cancel order',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1120,
        resolutions: 952,
        resolutionRate: '85%',
        csat: 3.8,
        tags: ['Eats customers', 'Riders'],
      },
      {
        id: 'w12',
        name: 'Report missing/damaged item',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 980,
        resolutions: 833,
        resolutionRate: '85%',
        csat: 3.7,
        tags: ['Eats customers'],
      },
      {
        id: 'w13',
        name: 'Delivery proof request',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 420,
        resolutions: 378,
        resolutionRate: '90%',
        csat: 4.1,
        tags: ['Eats customers', 'Riders'],
      },
      // Subscription Lifecycle agents
      {
        id: 'w14',
        name: 'Pause subscription',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 680,
        resolutions: 612,
        resolutionRate: '90%',
        csat: 4.2,
        tags: ['One members', 'Business riders'],
      },
      {
        id: 'w15',
        name: 'Resume subscription',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 340,
        resolutions: 306,
        resolutionRate: '90%',
        csat: 4.5,
        tags: ['One members'],
      },
      {
        id: 'w16',
        name: 'Failed payment recovery',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1840,
        resolutions: 1472,
        resolutionRate: '80%',
        csat: 3.6,
        tags: ['One members', 'Business riders', 'Riders'],
      },
      {
        id: 'w17',
        name: 'Change plan',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 920,
        resolutions: 782,
        resolutionRate: '85%',
        csat: 4.0,
        tags: ['One members', 'Business riders'],
      },
      // Payment Management agents
      {
        id: 'w18',
        name: 'Add/update payment method',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1420,
        resolutions: 1278,
        resolutionRate: '90%',
        csat: 4.1,
        tags: ['Riders', 'One members', 'Business riders'],
      },
      {
        id: 'w19',
        name: 'Dispute charge',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 780,
        resolutions: 624,
        resolutionRate: '80%',
        csat: 3.5,
        tags: ['Riders', 'Drivers'],
      },
      {
        id: 'w20',
        name: 'Apply promo code',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 2100,
        resolutions: 1890,
        resolutionRate: '90%',
        csat: 4.4,
        tags: ['Eats customers', 'Riders', 'One members'],
      },
      {
        id: 'w21',
        name: 'Split payment help',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 540,
        resolutions: 432,
        resolutionRate: '80%',
        csat: 3.9,
        tags: ['Eats customers', 'Business riders'],
      },
    ],
  },
  {
    // The Email channel historically borrowed the `webcall` key; now that Web
    // Call is its own channel below, Email has a key of its own.
    key: 'email',
    label: 'Email',
    metrics: [
      {
        key: 'chats',
        label: 'Total Conversations',
        value: '4,300',
        delta: '1.2%',
        trend: 'up',
        good: true,
      },
      {
        key: 'resolutions',
        label: 'Resolutions',
        value: '3,655',
        sub: '85%',
        delta: '0.8%',
        trend: 'up',
        good: true,
      },
      {
        key: 'fallback',
        label: 'Fallback',
        value: '128',
        delta: '1.1%',
        trend: 'down',
        good: true,
      },
      {
        key: 'csat',
        label: 'CSAT',
        value: '4.4',
        delta: '0.3%',
        trend: 'up',
        good: true,
        accent: true,
      },
      {
        key: 'cost',
        label: 'Cost Savings',
        value: '$164.5K',
        delta: '1.9%',
        trend: 'up',
        good: true,
      },
    ],
    agents: [
      {
        id: 'c1',
        name: 'Email escalation',
        on: true,
        isSubflow: true,
        type: 'With intent',
        conversations: 2100,
        resolutions: 1700,
        resolutionRate: '81%',
        csat: 4.4,
        tags: ['Business riders', 'Carriers'],
      },
    ],
  },
  {
    // Web Call — the in-browser voice channel (the Configuration screen's Web
    // Call studio). It sits next to Voice in the channel switcher. Eight-tile
    // strip and rows per the Webcall Use cases frame (Agent Builder_Use
    // case_001, 120:57534).
    key: 'webcall',
    label: 'Web Call',
    metrics: [
      {
        key: 'chats',
        label: 'Total Web Calls',
        value: '21,590',
        delta: '-0.3%',
        trend: 'down',
        good: false,
      },
      {
        key: 'talk',
        label: 'Total talk time',
        value: '73 hr 41 min',
        delta: '-1.7%',
        trend: 'down',
        good: false,
      },
      {
        key: 'avg-talk',
        label: 'Average talk time',
        value: '3 min 16 sec',
        delta: '+3.4%',
        trend: 'up',
        good: true,
      },
      {
        key: 'resolutions',
        label: 'Resolutions',
        value: '16,332',
        sub: '83%',
        delta: '+3.4%',
        trend: 'up',
        good: true,
      },
      {
        key: 'fallback',
        label: 'Fallback',
        value: '1,450',
        delta: '+2.4%',
        trend: 'up',
        good: false,
      },
      {
        key: 'sentiment',
        label: 'Positive & neutral sentiment',
        value: '87%',
        delta: '-0.3%',
        trend: 'down',
        good: false,
      },
      {
        key: 'csat',
        label: 'Average CSAT',
        value: '4.2',
        delta: '-2.1%',
        trend: 'down',
        good: false,
        accent: true,
      },
      {
        key: 'cost',
        label: 'Realized savings',
        value: '$25k',
        delta: '-1.7%',
        trend: 'down',
        good: false,
      },
    ],
    agents: [
      // Knowledge Retrieval and Fallback are the built-ins — fixed "On"
      // statuses rather than switches (canToggle false).
      {
        id: 'wc1',
        name: 'Knowledge Retrieval',
        on: true,
        canToggle: false,
        isSubflow: false,
        type: 'Knowledge Retrieval',
        conversations: 3000,
        resolutions: 2500,
        resolutionRate: '95%',
        csat: 4.2,
        tags: [],
        totalTalkTime: '19 hr 37 min',
      },
      {
        id: 'wc2',
        name: 'Fallback',
        on: true,
        canToggle: false,
        isSubflow: false,
        type: 'Fallback',
        conversations: 552,
        resolutions: 0,
        resolutionRate: 'n/a',
        csat: 0,
        tags: [],
        totalTalkTime: '5 hr 37 min',
      },
      {
        id: 'wc3',
        name: 'Payment',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1000,
        resolutions: 900,
        resolutionRate: '86%',
        csat: 4.0,
        tags: ['member_center', 'billing'],
        totalTalkTime: '6 hr 12 min',
      },
      {
        id: 'wc4',
        name: 'Login Help',
        on: false,
        isSubflow: false,
        type: 'Without intent',
        conversations: 0,
        resolutions: 0,
        resolutionRate: 'n/a',
        csat: 0,
        tags: ['fintech'],
        totalTalkTime: undefined,
      },
    ],
  },
  {
    key: 'voice',
    label: 'Voice',
    metrics: [
      { key: 'inboundCalls', label: 'Total inbound calls', value: '21,590', delta: '0.3%', trend: 'down', good: false },
      { key: 'eligibleCalls', label: 'Total eligible calls', value: '19,673', delta: '4.2%', trend: 'up', good: true },
      { key: 'talkTime', label: 'Total talk time', value: '334 hr 16 min', delta: '4.2%', trend: 'up', good: true },
      { key: 'avgTalkTime', label: 'Average Talk time', value: '2 min 28 sec', delta: '1.7%', trend: 'down', good: false },
      {
        key: 'resolutions',
        label: 'Resolutions',
        value: '7,973',
        sub: '98%',
        delta: '3.4%',
        trend: 'up',
        good: true,
      },
      {
        key: 'sentiment',
        label: 'Positive & neutral sentiment',
        value: '100%',
        delta: '0.3%',
        trend: 'down',
        good: false,
      },
      { key: 'csat', label: 'CSAT', value: '4.6', delta: '4.2%', trend: 'up', good: true, accent: true },
      { key: 'cost', label: 'Realized savings', value: '$119.6k', delta: '2.1%', trend: 'down', good: false },
    ],
    // Voice ▸ Outbound tiles, transcribed from frame 112:51124.
    outboundMetrics: [
      { key: 'outboundCalls', label: 'Total outbound calls', value: '5,000', delta: '0.3%', trend: 'down', good: false },
      { key: 'eligibleCalls', label: 'Eligible calls', value: '4,000', delta: '4.2%', trend: 'up', good: true },
      {
        key: 'engaged',
        label: 'Engaged',
        value: '3,800',
        sub: '80%',
        delta: '4.2%',
        trend: 'up',
        good: true,
      },
      {
        key: 'followUpAsks',
        label: 'Follow Up Asks',
        value: '50',
        sub: '10%',
        delta: '4.2%',
        trend: 'up',
        good: true,
      },
      { key: 'avgTalkTime', label: 'Average talk time', value: '3 min 16 sec', delta: '3.4%', trend: 'up', good: true },
      {
        key: 'sentiment',
        label: 'Positive & neutral sentiment',
        value: '90%',
        delta: '0.3%',
        trend: 'down',
        good: false,
      },
      { key: 'cost', label: 'Cost savings', value: '$3k', delta: '2.1%', trend: 'down', good: false },
      { key: 'talkTime', label: 'Total talk time', value: '73 hr 41 min', delta: '1.7%', trend: 'down', good: false },
    ],
    agents: [
      {
        id: 'v1',
        name: 'Call routing',
        on: true,
        isSubflow: false,
        type: 'Knowledge Retrieval',
        conversations: 4200,
        resolutions: 3600,
        resolutionRate: '86%',
        csat: 4.2,
        tags: ['Riders', 'Drivers'],
        canToggle: false,
        callDirection: 'inbound',
        segment: 'All segments',
        totalTalkTime: '19 hr 37 min',
        avgTalkTime: '1 min 12 sec',
        sentiment: '92%',
        contextVariables: ['Caller ID', 'Account tier'],
        actionsUsed: ['Route call', 'Verify identity'],
        subUseCases: ['Voicemail triage'],
        status: 'Published',
        lastModified: { at: 'Jan 4, 2026 9:25 AM', by: 'Brandon Mango' },
      },
      {
        id: 'v2',
        name: 'Voicemail triage',
        on: false,
        isSubflow: true,
        type: 'With intent',
        conversations: 1800,
        resolutions: 1200,
        resolutionRate: '67%',
        csat: 4,
        tags: ['Riders'],
        callDirection: 'inbound',
        segment: 'All segments',
        totalTalkTime: '4 hr 52 min',
        avgTalkTime: '48 sec',
        sentiment: '81%',
        contextVariables: ['Voicemail transcript'],
        actionsUsed: ['Transcribe voicemail', 'Tag urgency'],
        subUseCases: [],
        status: 'Draft',
        lastModified: { at: 'Dec 18, 2025 3:10 PM', by: 'Priya Shah' },
      },
      // Safety & Trust agents
      {
        id: 'v3',
        name: 'Report incident',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 420,
        resolutions: 420,
        resolutionRate: '100%',
        csat: 4.6,
        tags: ['Riders', 'Drivers'],
        callDirection: 'inbound',
        segment: 'Riders, Drivers',
        totalTalkTime: '3 hr 5 min',
        avgTalkTime: '2 min 36 sec',
        sentiment: '88%',
        contextVariables: ['Incident type', 'Location'],
        actionsUsed: ['Contact Human', 'Log incident'],
        subUseCases: ['Emergency contact'],
        status: 'Published',
        lastModified: { at: 'Feb 2, 2026 11:40 AM', by: 'Brandon Mango' },
      },
      {
        id: 'v4',
        name: 'Lost item recovery',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 1240,
        resolutions: 744,
        resolutionRate: '60%',
        csat: 3.8,
        tags: ['Riders', 'Eats customers'],
        callDirection: 'inbound',
        segment: 'Riders, Eats customers',
        totalTalkTime: '9 hr 18 min',
        avgTalkTime: '3 min 1 sec',
        sentiment: '79%',
        contextVariables: ['Trip ID', 'Item description'],
        actionsUsed: ['Contact driver', 'Log lost item'],
        subUseCases: [],
        status: 'Published',
        lastModified: { at: 'Jan 28, 2026 4:55 PM', by: 'Priya Shah' },
      },
      {
        id: 'v5',
        name: 'Rating dispute',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 680,
        resolutions: 476,
        resolutionRate: '70%',
        csat: 3.5,
        tags: ['Drivers', 'Couriers'],
        callDirection: 'inbound',
        segment: 'Drivers, Couriers',
        totalTalkTime: '5 hr 44 min',
        avgTalkTime: '2 min 10 sec',
        sentiment: '74%',
        contextVariables: ['Trip ID', 'Rating value'],
        actionsUsed: ['Review rating', 'Adjust rating'],
        subUseCases: [],
        status: 'Published',
        lastModified: { at: 'Jan 15, 2026 1:20 PM', by: 'Brandon Mango' },
      },
      {
        id: 'v6',
        name: 'Emergency contact',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 180,
        resolutions: 180,
        resolutionRate: '100%',
        csat: 4.8,
        tags: ['Riders'],
        callDirection: 'inbound',
        segment: 'Riders',
        totalTalkTime: '1 hr 30 min',
        avgTalkTime: '3 min 0 sec',
        sentiment: '95%',
        contextVariables: ['Location', 'Emergency type'],
        actionsUsed: ['Contact Human', 'Dispatch safety team'],
        subUseCases: ['Report incident'],
        status: 'Published',
        lastModified: { at: 'Feb 10, 2026 8:05 AM', by: 'Priya Shah' },
      },
      // Proactive Communication agents — company-initiated, so Outbound. Rows
      // transcribed from frame 112:51124; the table they feed is
      // VOICE_OUTBOUND_COLUMNS (Type / Use Case ID / Segment / calls / voicemail).
      {
        id: 'v7',
        name: 'Payment',
        on: true,
        isSubflow: false,
        type: 'Outbound',
        conversations: 1000,
        resolutions: 900,
        resolutionRate: '90%',
        csat: 4.4,
        // The Outbound table has no Tags column, but the fleet-wide seeds
        // invariant still requires named segments here.
        tags: ['Riders', 'Drivers'],
        callDirection: 'outbound',
        segment: 'All segments',
        useCaseId: '5d74aa9e-fcbf-42d4-9efd-6024',
        voicemailLeft: '50',
        subUseCases: [],
        status: 'Published',
        lastModified: { at: 'Jan 8, 2026 10:15 AM', by: 'Brandon Mango' },
      },
      {
        id: 'v8',
        name: 'Product Selection',
        on: true,
        isSubflow: true,
        type: 'Subflow',
        conversations: 0,
        resolutions: 0,
        // Not rendered anywhere — the Outbound table prints n/a for a subflow's
        // call columns — but the data tests pin resolutionRate to a percentage.
        resolutionRate: '0%',
        csat: 4.0,
        tags: ['Segment B'],
        callDirection: 'outbound',
        segment: 'Segment B',
        segmentColor: '#e2679e',
        useCaseId: '5d74aa9e-fcbf-42d4-9efd-6024',
        voicemailLeft: 'n/a',
        subUseCases: [],
        status: 'Published',
        lastModified: { at: 'Dec 30, 2025 2:45 PM', by: 'Priya Shah' },
      },
      {
        id: 'v9',
        name: 'Refund Subscription',
        on: true,
        isSubflow: false,
        type: 'Outbound',
        conversations: 500,
        resolutions: 450,
        resolutionRate: '90%',
        csat: 4.2,
        tags: ['Segment A'],
        callDirection: 'outbound',
        segment: 'Segment A',
        segmentColor: '#feca63',
        useCaseId: '5d74aa9e-fcbf-42d4-9efd-6024',
        voicemailLeft: '75',
        subUseCases: [],
        status: 'Published',
        lastModified: { at: 'Feb 5, 2026 6:00 AM', by: 'Brandon Mango' },
      },
    ],
  },
  {
    key: 'headless',
    label: 'Headless',
    metrics: [
      {
        key: 'chats',
        label: 'Total Sessions',
        value: '12,004',
        delta: '3.6%',
        trend: 'up',
        good: true,
      },
      {
        key: 'resolutions',
        label: 'Resolutions',
        value: '10,320',
        sub: '86%',
        delta: '2.2%',
        trend: 'up',
        good: true,
      },
      {
        key: 'fallback',
        label: 'Fallback',
        value: '640',
        delta: '2.4%',
        trend: 'down',
        good: true,
      },
      {
        key: 'csat',
        label: 'CSAT',
        value: '4.0',
        delta: '0.6%',
        trend: 'down',
        good: false,
        accent: true,
      },
      {
        key: 'cost',
        label: 'Cost Savings',
        value: '$402.1K',
        delta: '4.1%',
        trend: 'up',
        good: true,
      },
    ],
    agents: [
      {
        id: 'h1',
        name: 'API resolver',
        on: true,
        isSubflow: false,
        type: 'Knowledge Retrieval',
        conversations: 5000,
        resolutions: 4300,
        resolutionRate: '86%',
        csat: 4,
        tags: ['Health partners', 'Carriers'],
        canToggle: false,
      },
      {
        id: 'h2',
        name: 'Intent classifier',
        on: true,
        isSubflow: false,
        type: 'With intent',
        conversations: 3200,
        resolutions: 2600,
        resolutionRate: '81%',
        csat: 3.8,
        tags: ['Carriers'],
      },
      {
        id: 'h3',
        name: 'Fallback',
        on: false,
        isSubflow: false,
        type: 'Fallback',
        conversations: 1500,
        resolutions: 900,
        resolutionRate: '60%',
        csat: 3,
        tags: ['Health partners'],
      },
      {
        id: 'h4',
        name: 'Enrichment',
        on: true,
        isSubflow: true,
        type: 'With intent',
        conversations: 2304,
        resolutions: 1800,
        resolutionRate: '78%',
        csat: 4,
        tags: ['Business riders', 'Carriers'],
      },
    ],
  },
]
